/**
 *
 */
package controladores;

/**
 * @author ra00228542
 *
 */
public enum TipoDesenho {
    RETA, CIRCULO, PONTO, CURVA_DO_DRAGAO, RETA_ELASTICA, CIRCULO_ELASTICO, RETANGULO_ELASTICO, POLIGONO_ELASTICO,
    RETA_POLIGONAL, SELECIONA_DESENHO,
}
